export { default as Home  } from './HomePage'
export { default as Rules } from './Rules'
export { default as User  } from './User'
export { default as Intro } from './Intro'
export { default as Photo } from './Photo'
export { default as Diary } from './Diary'
export { default as Map   } from './Map'
export { default as Money } from './Money'
export { default as Signup} from './Signup'
export { default as AddTrip  } from './AddTrip'
export { default as AddPhoto } from './AddPhoto'
export { default as AddDiary } from './AddDiary'
