# Generated by Django 2.0.4 on 2018-06-08 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contents', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('diaries', models.ManyToManyField(blank=True, related_name='photos', to='trips.Diary')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_in_folder', to='trips.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinceWhen', models.DateField()),
                ('tilWhen', models.DateField()),
                ('contents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sinceWhen', models.DateField()),
                ('tilWhen', models.DateField()),
                ('creator', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='my_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_todo', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_schedule', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='rule',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_rule', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_photo', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='marker',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_marker', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='folder',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_folder', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_expense', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='diary',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_diary', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='diary',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_diary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_budget', to='trips.Trip'),
        ),
    ]
